name: agroneo_treeplace
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0
  web_socket_channel: 1.1.0
  url_launcher: 5.4.1
  uni_links: 0.2.0
  shared_preferences: 0.5.6
  cupertino_icons: ^0.1.2
  html_unescape: 1.0.1+3
  photo_view: 0.9.0
  google_maps_flutter: 0.5.21+3
  clustering_google_maps: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/

