name: agroneo_treeplace
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0
  url_launcher: 5.4.1
  uni_links: 0.2.0
  shared_preferences: 0.5.6
  cached_network_image: 2.0.0-rc.1
  cupertino_icons: ^0.1.2
  html_unescape: 1.0.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

